# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171020_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='associate',
            old_name='location',
            new_name='facility',
        ),
    ]
