# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171021_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitygoal',
            name='goalAmount',
            field=models.IntegerField(),
        ),
    ]
