# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171021_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='coaEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntered', models.DateField(auto_now_add=True)),
                ('facility', models.CharField(max_length=10)),
                ('enteringUser', models.CharField(max_length=10)),
                ('questionOne', models.CharField(max_length=1000)),
                ('questionTwo', models.CharField(max_length=1000)),
                ('questionThree', models.CharField(max_length=1000)),
                ('askedUser', models.CharField(max_length=10)),
                ('answerOne', models.CharField(max_length=1000)),
                ('answerTwo', models.CharField(max_length=1000)),
                ('answerThree', models.CharField(max_length=1000)),
            ],
        ),
    ]
