# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_coaentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='coaQuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('questionOne', models.CharField(max_length=1000)),
                ('questionTwo', models.CharField(max_length=1000)),
                ('questionThree', models.CharField(max_length=1000)),
            ],
        ),
    ]
