# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_coaquestionbank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coaEntries',
            new_name='coaEntry',
        ),
    ]
