# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20171021_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='coaEntry',
        ),
        migrations.DeleteModel(
            name='coaQuestionBank',
        ),
        migrations.DeleteModel(
            name='facilityGoal',
        ),
    ]
