# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coaEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEntered', models.DateField(auto_now_add=True)),
                ('facility', models.CharField(max_length=10)),
                ('enteringUser', models.CharField(max_length=10)),
                ('questionOne', models.CharField(max_length=1000)),
                ('questionTwo', models.CharField(max_length=1000)),
                ('questionThree', models.CharField(max_length=1000)),
                ('askedUser', models.CharField(max_length=10)),
                ('answerOne', models.CharField(max_length=1000)),
                ('answerTwo', models.CharField(max_length=1000)),
                ('answerThree', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='coaQuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=10)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('questionOne', models.CharField(max_length=1000)),
                ('questionTwo', models.CharField(max_length=1000)),
                ('questionThree', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='facilityGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=10)),
                ('goalType', models.CharField(max_length=100)),
                ('goalDuration', models.CharField(max_length=100)),
                ('goalAmount', models.IntegerField()),
            ],
        ),
    ]
